python main.py                                                          \
    --dataset="/dataset/yelp"	    	                                \
    --train_batch_size=100000                                           \
    --test_batch_size=10000                                             \
    --shuffle=True                                                      \
    --num_epoch=20                                                      \
    --lr=0.005                                                          \
    --momentum=0.9                                                      \
    --latent_dim=30                                                     \
    --K=5                                                               \
    --use_cuda=True
